### PR TITLE
And Support for custom email sender function and update es locale

### PR DESCRIPTION
**Pull request by luisza**
Hi,

With this PR will support a custom email function, and include the possibility to turn off email notifications.
I update README to include the new settings variables (all optional)

I am developing https://github.com/luisza/async_notifications that manage how email is send, So I don't like to manage with template approach.

I update MANIFEST.in include locale folder (pip version right now haven't locale support).

### CODE REVIEW

**Comment by jvamvas** [comment]
Hi Luis, thanks for the Pull Request. There are clearly some great ideas:

- The MANIFEST.in fix
- The possibility to disable email

Could you please go into a little more detail on what the advantages of CONTACT_PLUS_SEND_METHOD are compared to the django EMAIL_BACKEND setting?

**Comment by luisza** [comment]
Yes of course.

In email backend is used by provide a way to send a email, working with the connection, so.with this approach you can change the method of how django send the email eg sendmail or SMTP .
I think probably I can adjust my code to provide a email backend with celery but the functionality in this PR do more than I need.
Thinking what could be do using

**Comment by luisza** [comment]
Yes of course.

In email backend is used by provide a way to send a email, working with the connection, so.with this approach you can change the method of how django send the email eg sendmail or SMTP , but is not please for decision based on email content.
I think probably I can adjust my code to provide a email backend with celery but the functionality in this PR do more than I need.
Thinking what could be do using CONTACT_PLUS_SEND_METHOD  I found

- create a basic ticket system, overwriting email field and including an department field in form with a little effort
- filter email based in the content ( you can not filter an email in clean method in form), you also can incorporate something like spamassist 
- call other signals not just email send signal
- send a copy to predefined email (signal can do this)
- send email with different email server, so all system can send with one trusty server and the public contact form use a hardness email server. ( you can not do this with email backend, I think)

There is a lot of possibilities you can do with this new function

**Comment by jvamvas** [comment]
Thanks for the clarification 👍 

I have released a new minor version with your MANIFEST.in fix. For the CONTACT_PLUS_SEND_METHOD setting, I think it would rather be material for a major release, because of the implications it would have on the scope and configurability of the plugin. We will keep your PR in mind until we plan the next major release :)

**Comment by luisza** [comment]
cool, thanks

**Pull request closed without merging**
