### PR TITLE
New migrations are no longer made for every settings.ADMINS change

### PR DESCRIPTION
**Pull request by raiderrobert**
Replaced explicit constant call with callable and updated migrations to match. This pattern is the [best practice](http://stackoverflow.com/a/12654998) for how to accomplish this kind of problem.

### CODE REVIEW

**Comment by jvamvas** [comment]
Note: This PR is compatible with Django >= 1.7

**Comment by raiderrobert** [comment]
@jvamva, that's correct.

**Comment by philippeowagner** [comment]
@raiderrobert @jvamvas I did not noticed this PR up to now. My fault, sorry... 
Could it still be merged?  

@raiderrobert thanks for your contribution.

**Comment by raiderrobert** [comment]
Hey @philippeowagner, this change is very old at this point. It has some merge conflicts in it, and given the time that's gone by, I'm not sure of the impact of some of things to reconcile in the request. Additionally, I don't have time right now to reconcile them. Feel free to take it, but I was just trying to clean up old PRs.

**Comment by walterrenner** [comment]
I cherry picked the changes in 58dbc76d6cf2b4cc499e4ca5d4b11d762d7c0a19.

This will be fixed in the next release. Thanks @raiderrobert for pointing this out.

**Pull request closed without merging**
